# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Szablon", name: "layout", widget: "hidden", default: "post"}
      - {label: "Tytuł", name: "title", widget: "string", tagname: "h1"}
      - label: "Author"
        name: "author"
        widget: "select"
        options:
          - { label: "Jakub Godawa", value: "jakub_godawa" }
      - {label: "Data publikacji", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:MM:SS"}
      - {label: "Krótkie wprowadzenie", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Część główna", name: "body", widget: "markdown", required: false}
      - {label: "Kategorie", name: "categories", widget: "string", required: false}
    # PAGES
  - name: "page"
    label: "Strona"
    folder: "pages"
    sort: "title:asc"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Szablon", name: "layout", widget: "hidden", default: "page"}
      - {label: "Tytuł", name: "title", widget: "string", tagname: "h1"}
      - {label: "Adres", name: "permalink", widget: "hidden"}
      - {label: "Sekcja", name: "section", widget: "hidden", default: "{{name}}"}
      - {label: "Krótkie wprowadzenie", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Część główna", name: "body", widget: "markdown", required: false}
